name: terraform
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: terraform fmt -check -recursive -diff